export enum Services {
  CHAT_SERVICE = 'CHAT_SERVICE',
  CHAT_CAMPAIGN_SERVICE = 'CHAT_CAMPAIGN_SERVICE',
  QUEUE_CHAT_SERVICE = 'QUEUE_CHAT_SERVICE',
}

export enum Repositories {
  CHAT_REPOSITORY = 'CHAT_REPOSITORY',
  CHAT_PROVIDER_SERVICE = 'CHAT_PROVIDER_SERVICE',
}
